### PR TITLE
NF: Mobile Responsive screens

### PR DESCRIPTION
**Pull request by deka27**
This PR adds mobile & tablet responsiveness to screens.

### CODE REVIEW

**Comment by maharshi-gor** [comment]
Hey @deka27 

I checked the PR on mobile version it gives few issues

Screenshot from 2024-10-30 12-54-59

The description looks to narrow make it text-align justified or reduce the padding around it.

Screenshot from 2024-10-30 12-54-27
The box are going out of the screen.

**Review by maharshi-gor — APPROVED** [review]
LGTM

**Review by skoudoro — CHANGES_REQUESTED** [review]
Hi @deka27, 

Thank for the update, see below some issues:

- Missing the image below:
image

- black background not needed, the white logo is enought. Can you remove it?

image

**Review by skoudoro — APPROVED** [review]
Thank you for fixing this. 

all good, Thank you for this work @deka27. 

Merging

**Pull request merged**
